name: News Mail

on:
  push:
    branches:
      - master
  schedule:
    - cron: '05 23 * * *'

env:
  MAIL_PASSWORD: "${{ secrets.MAIL_PASSWORD }}"
  MAIL_TO: "${{ secrets.MAIL_TO }}"
  MAIL_USERNAME: "${{ secrets.MAIL_USERNAME }}"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '8'
      - run: sh start.sh
